version: '3'
services:
  client:
    restart: always
    container_name: ac-cli
    build:
      context: .
      dockerfile: Dockerfile.production
    networks:
      - ac
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - ac
      
networks:
  ac:
    external: true