FROM node:20-bullseye-slim as build-stage

WORKDIR /app
RUN apt update && apt upgrade -y
COPY package*.json /app/
COPY nginx.conf /nginx.conf

RUN npm install

COPY ./ /app/

RUN npm run build

FROM nginx:1.25-alpine

EXPOSE 80

COPY --from=build-stage /app/dist/ /usr/share/nginx/html

COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf
