FROM node:16-bullseye-slim as build-stage

WORKDIR /app
RUN apt update && apt upgrade -y
COPY package*.json /app/
COPY nginx.conf /nginx.conf

RUN npm install

COPY ./ /app/

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.25
EXPOSE 8080

COPY --from=build-stage /app/dist/ /usr/share/nginx/html

COPY public/image /usr/share/nginx/html/image

COPY --from=build-stage /nginx.conf /etc/nginx/conf.d/default.conf